version: 2.1

executors:
  maven-executor:
    docker:
      - image: circleci/openjdk:17-jdk-buster
    working_directory: ~/project

jobs:
  test:
    executor: maven-executor
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: mvn dependency:go-offline -B

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # Running the tests
      - run:
          name: Run tests
          command: mvn test

  # Job to build the project
  build:
    executor: maven-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run:
          name: Build the project
          command: mvn clean install

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build
